#!/usr/bin/env ruby

require 'bundler/setup'
require 'optparse'
require 'panther'
require 'panther/rack/builder'

options = { config: 'config.ru', port: 7152, host: 'localhost' }

OptionParser.new do |opts|
  opts.banner = 'Usage: panther [options]'

  opts.on('-c', '--config [String]', 'config') do |v|
    options[:config] = v
  end

  opts.on('-h', '--host [String]', 'host') do |v|
    options[:host] = v
  end

  opts.on('-p', '--port [Integer]', 'listen port') do |v|
    options[:port] = v
  end

  opts.on('-k', '--key [String]', 'SSL key') do |v|
    options[:key] = v
  end

  opts.on('-c', '--cert [String]', 'SSL cert') do |v|
    options[:cert] = v
  end
end.parse!

app = Panther::Rack::Builder.build(options.fetch(:config))
Panther::Server.new(app, options).run
